# Generated by Django 4.2.1 on 2023-06-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengers',
            name='flight',
        ),
        migrations.AddField(
            model_name='passengers',
            name='flight',
            field=models.ManyToManyField(blank=True, null=True, related_name='passengers', to='flights.flights'),
        ),
    ]
