# Generated by Django 4.2.1 on 2023-06-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_remove_passengers_flight_passengers_flight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passengers',
            old_name='flight',
            new_name='flights',
        ),
        migrations.AlterField(
            model_name='airports',
            name='Code',
            field=models.CharField(max_length=4),
        ),
    ]
