# Generated by Django 4.2.1 on 2023-06-06 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_rename_flight_passengers_flights_alter_airports_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Airports',
            new_name='Airport',
        ),
        migrations.RenameModel(
            old_name='Flights',
            new_name='Flight',
        ),
        migrations.RenameModel(
            old_name='Passengers',
            new_name='Passenger',
        ),
    ]
