# Generated by Django 4.2.1 on 2023-06-06 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_rename_airports_airport_rename_flights_flight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='person',
            new_name='people',
        ),
    ]
