# Generated by Django 4.2.1 on 2023-06-06 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_rename_people_passenger_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='person',
            new_name='people',
        ),
    ]
