name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          NAME: flightDB
          USER: postgres
          PASSWORD: badnaccy13
          HOST: localhost
        ports: 
          - 5433:5432
    steps:
    - uses: actions/checkout@v3
    - name: Run Django unit tests
      run: |
        pip install -r requirements.txt
        python -m pip install --upgrade pip
        pip3 install --user django
        python3 manage.py test